"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-0myiqphlp=208&g6i!27qg2ucvqlh$ib77klvj6fs^px)j+k^#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "simpleui",          # ✅ SimpleUI（必须在 admin 之前）
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",  # ✅ DRF注册
    "rest_framework.authtoken",  # ✅ DRF Token认证
    "corsheaders",     # ✅ 跨域注册
    
    # 你的业务App（保持原有顺序不变）
    "apps.ai_chat",                     # ai客服应用
    "apps.analysis",                    # 数据分析+可视化应用
    "apps.jobs",                        # 岗位数据管理应用
    "apps.ml_models",                   # ML模型（薪资预测/推荐/简历匹配）
    "apps.spider",                      # 爬虫应用
    "apps.users",                       # 用户管理应用
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # ✅ 跨域中间件放第一个
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "job_analysis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "job_analysis" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "job_analysis.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "liepin_analysis_db",
        "USER": "root",
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------------------- 自定义用户模型 --------------------------
AUTH_USER_MODEL = "users.User"

# -------------------------- DRF 配置 --------------------------
REST_FRAMEWORK = {
    # 全局分页配置（所有列表接口默认分页）
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,  # 每页返回20条数据

    # 全局认证类（使用Token认证，禁用Session认证避免CSRF问题）
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],

    # 全局权限类（开发阶段用AllowAny，上线改成IsAuthenticated）
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],

    # 响应渲染器（djangorestframework-camel-case 自动 snake_case → camelCase）
    "DEFAULT_RENDERER_CLASSES": [
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
    ],

    # 请求解析器（自动 camelCase → snake_case，前端发驼峰后端自动转下划线）
    "DEFAULT_PARSER_CLASSES": [
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
    ],

    # 日期时间格式统一
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    "DATE_FORMAT": "%Y-%m-%d",
    "TIME_FORMAT": "%H:%M:%S",
}

# -------------------------- SimpleUI 配置 --------------------------
SIMPLEUI_DEFAULT_THEME = "element"
SIMPLEUI_HOME_TITLE = "招聘数据分析平台"
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

SIMPLEUI_CONFIG = {
    "system_keep": False,
    "menu_display": ["用户中心", "岗位数据"],
    "dynamic": True,
    "menus": [
        {
            "app": "users",
            "name": "用户中心",
            "icon": "fas fa-users",
            "models": [
                {"name": "用户列表", "icon": "far fa-user", "url": "users/user/"},
                {"name": "用户资料", "icon": "far fa-address-card", "url": "users/userprofile/"},
                {"name": "用户收藏", "icon": "fas fa-star", "url": "users/favorite/"},
                {"name": "浏览历史", "icon": "fas fa-history", "url": "users/browsehistory/"},
            ],
        },
        {
            "app": "jobs",
            "name": "岗位数据",
            "icon": "fas fa-briefcase",
            "models": [
                {"name": "岗位列表", "icon": "fas fa-list", "url": "jobs/job/"},
            ],
        },
    ],
}

# -------------------------- 跨域配置 --------------------------
CORS_ALLOW_ALL_ORIGINS = True   # 开发环境用，上线改成具体域名
CORS_ALLOW_CREDENTIALS = True   # 解决前端跨域

# -------------------------- CSRF 配置（完全禁用）--------------------------
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_DOMAIN = None
CSRF_TRUSTED_ORIGINS = []

# -------------------------- AI 模型配置 --------------------------
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
DEEPSEEK_MODEL = "deepseek-chat" 

# -------------------------- 内网穿透配置 --------------------------
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "https://6c11684d.r34.cpolar.top"]  # 后端隧道的域名
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://78385020.r34.cpolar.top",  # 前端隧道的域名
]
# ====== 内网穿透配置（cpolar）======
# 前端隧道域名：5c2024fb.r34.cpolar.top
# 后端隧道域名：2d4e2651.r34.cpolar.top
# 注意：cpolar 免费版每次重启域名会变，需要同步更新 ALLOWED_HOSTS 和 CORS
# 热力图用的 中国地图 GeoJSON 数据 是从阿里云 DataV 的 CDN 实时拉取的，需要referrerPolicy: 'no-referrer' 来解决跨域问题

# 启动后端隧道、前端隧道、Django后端（启动前先更新 settings.py 里的新域名）、Vite前端（启动前先更新 vite.config.js 里的新域名）