"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-0myiqphlp=208&g6i!27qg2ucvqlh$ib77klvj6fs^px)j+k^#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "simpleui",          # ✅ SimpleUI（必须在 admin 之前）
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",  # ✅ DRF注册
    "rest_framework.authtoken",  # ✅ DRF Token认证
    "corsheaders",     # ✅ 跨域注册
    
    # 你的业务App（保持原有顺序不变）
    "apps.ai_chat",                     # ai客服应用
    "apps.analysis",                    # 数据分析+可视化应用
    "apps.jobs",                        # 岗位数据管理应用
    "apps.ml_models",                   # ML模型（薪资预测/推荐/简历匹配）
    "apps.spider",                      # 爬虫应用
    "apps.users",                       # 用户管理应用
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # ✅ 跨域中间件放第一个
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "job_analysis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "job_analysis" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "job_analysis.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "liepin_analysis_db",
        "USER": "root",
        "PASSWORD": "***REMOVED***",
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------------------- 自定义用户模型 --------------------------
AUTH_USER_MODEL = "users.User"

# -------------------------- DRF 配置 --------------------------
REST_FRAMEWORK = {
    # 全局分页配置（所有列表接口默认分页）
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,  # 每页返回20条数据

    # 全局认证类（使用Token认证，禁用Session认证避免CSRF问题）
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],

    # 全局权限类（开发阶段用AllowAny，上线改成IsAuthenticated）
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],

    # 响应渲染器（支持JSON和浏览器API界面）
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],

    # 日期时间格式统一
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    "DATE_FORMAT": "%Y-%m-%d",
    "TIME_FORMAT": "%H:%M:%S",
}

# -------------------------- SimpleUI 配置 --------------------------
SIMPLEUI_DEFAULT_THEME = "element"
SIMPLEUI_HOME_TITLE = "招聘数据分析平台"
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

SIMPLEUI_CONFIG = {
    "system_keep": False,
    "menu_display": ["仪表盘", "用户中心", "岗位数据", "数据分析", "机器学习", "爬虫中心", "AI 客服", "系统管理"],
    "dynamic": True,
    "menus": [
        {
            "name": "仪表盘",
            "icon": "fas fa-chart-line",
            "url": "/admin/dashboard/",
        },
        {
            "app": "users",
            "name": "用户中心",
            "icon": "fas fa-users",
            "models": [
                {"name": "用户列表", "icon": "far fa-user", "url": "users/user/"},
                {"name": "用户资料", "icon": "far fa-address-card", "url": "users/userprofile/"},
                {"name": "用户收藏", "icon": "fas fa-star", "url": "users/favorite/"},
                {"name": "浏览历史", "icon": "fas fa-history", "url": "users/browsehistory/"},
            ],
        },
        {
            "app": "jobs",
            "name": "岗位数据",
            "icon": "fas fa-briefcase",
            "models": [
                {"name": "岗位列表", "icon": "fas fa-list", "url": "jobs/job/"},
            ],
        },
        {
            "app": "analysis",
            "name": "数据分析",
            "icon": "fas fa-chart-bar",
            "models": [
                {"name": "分析报告", "icon": "fas fa-file-alt", "url": "analysis/analysisreport/"},
            ],
        },
        {
            "app": "ml_models",
            "name": "机器学习",
            "icon": "fas fa-brain",
            "models": [
                {"name": "模型列表", "icon": "fas fa-cube", "url": "ml_models/mlmodel/"},
                {"name": "薪资预测", "icon": "fas fa-dollar-sign", "url": "ml_models/salaryprediction/"},
                {"name": "推荐记录", "icon": "fas fa-thumbs-up", "url": "ml_models/recommendationlog/"},
                {"name": "简历匹配", "icon": "fas fa-file-invoice", "url": "ml_models/resumematchresult/"},
            ],
        },
        {
            "app": "spider",
            "name": "爬虫中心",
            "icon": "fas fa-server",
            "models": [
                {"name": "爬虫任务", "icon": "fas fa-tasks", "url": "spider/spidertask/"},
                {"name": "爬虫控制台", "icon": "fas fa-play-circle", "url": "/admin/spider-control/"},
            ],
        },
        {
            "app": "ai_chat",
            "name": "AI 客服",
            "icon": "fas fa-comments",
            "models": [
                {"name": "对话记录", "icon": "fas fa-comment-dots", "url": "ai_chat/chatmessage/"},
            ],
        },
        {
            "name": "系统管理",
            "icon": "fas fa-cog",
            "models": [
                {"name": "用户", "icon": "fas fa-user", "url": "auth/user/"},
                {"name": "组", "icon": "fas fa-users-cog", "url": "auth/group/"},
            ],
        },
    ],
}

# -------------------------- 跨域配置 --------------------------
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境用，上线改成具体域名
CORS_ALLOW_CREDENTIALS = True

# -------------------------- CSRF 配置（完全禁用）--------------------------
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_DOMAIN = None
CSRF_TRUSTED_ORIGINS = []
