# Generated by Django 5.2.14 on 2026-06-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="expected_category",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="期望岗位"
            ),
        ),
    ]
