# Generated by Django 6.0.5 on 2026-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="搜索关键词"
                    ),
                ),
                (
                    "job_url",
                    models.URLField(blank=True, default="", verbose_name="岗位链接"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="岗位名称")),
                (
                    "salary",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="薪资文本"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="地点"
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="经验要求"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="学历要求"
                    ),
                ),
                (
                    "recruit_count",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="招聘人数"
                    ),
                ),
                (
                    "update_time",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="更新时间"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="公司名称"
                    ),
                ),
                (
                    "company_link",
                    models.URLField(blank=True, default="", verbose_name="公司链接"),
                ),
                (
                    "job_description",
                    models.TextField(blank=True, default="", verbose_name="岗位描述"),
                ),
                (
                    "language_requirement",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="语言要求"
                    ),
                ),
                (
                    "industry_requirement",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="行业要求"
                    ),
                ),
                (
                    "work_time",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="工作时间"
                    ),
                ),
                (
                    "company_tags",
                    models.JSONField(blank=True, default=list, verbose_name="公司标签"),
                ),
                (
                    "crawl_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="爬取时间"
                    ),
                ),
                (
                    "month_salary_min",
                    models.FloatField(blank=True, null=True, verbose_name="月薪下限"),
                ),
                (
                    "month_salary_max",
                    models.FloatField(blank=True, null=True, verbose_name="月薪上限"),
                ),
                (
                    "location_city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="城市"
                    ),
                ),
                (
                    "location_province",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="省份"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="岗位类别"
                    ),
                ),
                (
                    "tokenized_words",
                    models.TextField(blank=True, default="", verbose_name="分词结果"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "岗位",
                "verbose_name_plural": "岗位",
                "ordering": ["-created_at"],
            },
        ),
    ]
