# Generated by Django 6.0.5 on 2026-05-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="has_language_requirement",
            field=models.BooleanField(default=False, verbose_name="有外语要求"),
        ),
        migrations.AddField(
            model_name="job",
            name="has_weekend_off",
            field=models.BooleanField(default=False, verbose_name="周末双休"),
        ),
        migrations.AddField(
            model_name="job",
            name="recruit_count_parsed",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="招聘人数(解析)"
            ),
        ),
    ]
