# Generated by Django 6.0.5 on 2026-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_has_language_requirement_job_has_weekend_off_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Java开发", "Java开发"),
                    ("Python开发", "Python开发"),
                    ("Go开发", "Go开发"),
                    ("C++开发", "C++开发"),
                    ("PHP开发", "PHP开发"),
                    ("爬虫工程师", "爬虫工程师"),
                    ("嵌入式开发", "嵌入式开发"),
                    ("前端", "前端"),
                    ("全栈", "全栈"),
                    ("运维", "运维"),
                    ("算法", "算法"),
                ],
                default="",
                max_length=100,
                verbose_name="岗位类别",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("大专", "大专"),
                    ("本科", "本科"),
                    ("统招本科", "统招本科"),
                    ("硕士", "硕士"),
                    ("博士", "博士"),
                    ("学历不限", "学历不限"),
                ],
                default="",
                max_length=50,
                verbose_name="学历要求",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("经验不限", "经验不限"),
                    ("实习", "实习"),
                    ("应届", "应届"),
                    ("1年以下", "1年以下"),
                    ("1年以上", "1年以上"),
                    ("2年以上", "2年以上"),
                    ("3年以上", "3年以上"),
                    ("4年以上", "4年以上"),
                    ("5年以上", "5年以上"),
                    ("6年以上", "6年以上"),
                    ("8年以上", "8年以上"),
                    ("10年以上", "10年以上"),
                    ("1-3年", "1-3年"),
                    ("2-5年", "2-5年"),
                    ("3-5年", "3-5年"),
                    ("3-6年", "3-6年"),
                    ("5-10年", "5-10年"),
                ],
                default="",
                max_length=50,
                verbose_name="经验要求",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="recruit_count",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="招聘人数(原始)"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="recruit_count_parsed",
            field=models.IntegerField(blank=True, null=True, verbose_name="招聘人数"),
        ),
    ]
