# Generated by manual

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_category_alter_job_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_industry",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="公司行业"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="company_scale_min",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="公司规模下限"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="company_scale_max",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="公司规模上限"
            ),
        ),
    ]
