# Generated by manual

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_company_industry_job_company_scale_min_job_compan"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_scale",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="公司规模"
            ),
        ),
    ]
