# Generated by Django 5.2.14 on 2026-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_company_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="month_salary_avg",
            field=models.FloatField(blank=True, null=True, verbose_name="月薪均值"),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("经验不限", "经验不限"),
                    ("实习", "实习"),
                    ("应届", "应届"),
                    ("1年以下", "1年以下"),
                    ("1年以上", "1年以上"),
                    ("2年以上", "2年以上"),
                    ("3年以上", "3年以上"),
                    ("4年以上", "4年以上"),
                    ("5年以上", "5年以上"),
                    ("6年以上", "6年以上"),
                    ("8年以上", "8年以上"),
                    ("10年以上", "10年以上"),
                    ("1-3年", "1-3年"),
                    ("2-5年", "2-5年"),
                    ("3-5年", "3-5年"),
                    ("3-6年", "3-6年"),
                    ("5-10年", "5-10年"),
                    ("1-8年", "1-8年"),
                    ("2-8年", "2-8年"),
                    ("1-10年", "1-10年"),
                ],
                default="",
                max_length=50,
                verbose_name="经验要求",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="recruit_count_parsed",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="招聘人数(解析)"
            ),
        ),
    ]
