# Generated by Django 6.0.5 on 2026-05-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_job_month_salary_avg_alter_job_experience_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="key",
        ),
    ]
