# Generated by Django 6.0.5 on 2026-05-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_remove_job_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="key",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="搜索关键词"
            ),
        ),
    ]
