# Generated by Django 5.2.14 on 2026-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_job_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location_partition",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="分区"
            ),
        ),
    ]
