# Generated by Django 5.2.14 on 2026-05-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_job_location_partition"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience_level",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="经验等级"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="岗位类别"
            ),
        ),
    ]
