# Generated by Django 5.2.14 on 2026-05-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_job_experience_level_alter_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="update_time_parsed",
            field=models.DateField(blank=True, null=True, verbose_name="更新时间解析"),
        ),
    ]
