# Generated by Django 5.2.14 on 2026-05-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_update_time_parsed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="update_time_parsed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="更新时间解析"
            ),
        ),
    ]
