# Generated by Django 6.0.5 on 2026-05-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="模型名称")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("salary_predictor", "薪资预测器"),
                            ("recommender", "推荐模型"),
                            ("resume_matcher", "简历匹配器"),
                        ],
                        max_length=50,
                        verbose_name="模型类型",
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(blank=True, null=True, verbose_name="准确率"),
                ),
                (
                    "f1_score",
                    models.FloatField(blank=True, null=True, verbose_name="F1分数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "ML模型",
                "verbose_name_plural": "ML模型",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeMatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(default=0.0, verbose_name="相似度"),
                ),
                (
                    "matched_keywords",
                    models.TextField(blank=True, default="", verbose_name="匹配关键词"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="匹配时间"),
                ),
            ],
            options={
                "verbose_name": "简历匹配结果",
                "verbose_name_plural": "简历匹配结果",
                "ordering": ["-similarity_score"],
            },
        ),
        migrations.CreateModel(
            name="SalaryPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="城市"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="岗位类别"
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(default=0, verbose_name="工作经验(年)"),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="学历"
                    ),
                ),
                (
                    "work_time",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="工作时间"
                    ),
                ),
                (
                    "language_requirement",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="语言要求"
                    ),
                ),
                (
                    "predicted_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="预测最低薪资(K)"
                    ),
                ),
                (
                    "predicted_mid",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="预测中位薪资(K)"
                    ),
                ),
                (
                    "predicted_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="预测最高薪资(K)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="预测时间"),
                ),
            ],
            options={
                "verbose_name": "薪资预测",
                "verbose_name_plural": "薪资预测",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0, verbose_name="推荐分数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="推荐时间"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to="jobs.job",
                        verbose_name="推荐岗位",
                    ),
                ),
            ],
            options={
                "verbose_name": "推荐记录",
                "verbose_name_plural": "推荐记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
