# Generated by Django 5.2.14 on 2026-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationlog",
            name="strategy",
            field=models.CharField(
                blank=True, default="hybrid", max_length=20, verbose_name="推荐策略"
            ),
        ),
    ]
