# Generated by Django 5.2.14 on 2026-06-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0003_recommendationlog_strategy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salaryprediction",
            name="experience_years",
        ),
        migrations.RemoveField(
            model_name="salaryprediction",
            name="language_requirement",
        ),
        migrations.RemoveField(
            model_name="salaryprediction",
            name="predicted_mid",
        ),
        migrations.RemoveField(
            model_name="salaryprediction",
            name="work_time",
        ),
        migrations.AddField(
            model_name="salaryprediction",
            name="company_industry",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="公司行业"
            ),
        ),
        migrations.AddField(
            model_name="salaryprediction",
            name="company_scale",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="公司规模"
            ),
        ),
        migrations.AddField(
            model_name="salaryprediction",
            name="experience_level",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="经验等级"
            ),
        ),
        migrations.AddField(
            model_name="salaryprediction",
            name="feature_importance",
            field=models.JSONField(blank=True, default=list, verbose_name="特征重要性"),
        ),
        migrations.AddField(
            model_name="salaryprediction",
            name="model_used",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="使用的模型"
            ),
        ),
        migrations.AddField(
            model_name="salaryprediction",
            name="predicted_salary",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="预测薪资(K)"
            ),
        ),
    ]
