# Generated by Django 5.2.14 on 2026-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0004_remove_salaryprediction_experience_years_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resumematchresult",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "简历匹配结果",
                "verbose_name_plural": "简历匹配结果",
            },
        ),
        migrations.RemoveField(
            model_name="resumematchresult",
            name="job",
        ),
        migrations.RemoveField(
            model_name="resumematchresult",
            name="matched_keywords",
        ),
        migrations.RemoveField(
            model_name="resumematchresult",
            name="similarity_score",
        ),
        migrations.AddField(
            model_name="resumematchresult",
            name="results",
            field=models.JSONField(blank=True, default=dict, verbose_name="匹配结果"),
        ),
        migrations.AddField(
            model_name="resumematchresult",
            name="total_count",
            field=models.IntegerField(default=0, verbose_name="匹配结果数"),
        ),
    ]
