# Generated by Django 5.2.14 on 2026-06-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0005_alter_resumematchresult_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendationlog",
            name="job",
        ),
        migrations.RemoveField(
            model_name="recommendationlog",
            name="score",
        ),
        migrations.AddField(
            model_name="recommendationlog",
            name="results",
            field=models.JSONField(blank=True, default=list, verbose_name="推荐结果"),
        ),
    ]
